# Generated by Django 2.2.12 on 2020-05-01 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=2000)),
                ('answer1', models.TextField()),
                ('answer2', models.TextField(blank=True, null=True)),
                ('answer3', models.TextField(blank=True, null=True)),
                ('faq_img1', models.ImageField(blank=True, null=True, upload_to='faq')),
                ('faq_img2', models.ImageField(blank=True, null=True, upload_to='faq')),
                ('faq_img3', models.ImageField(blank=True, null=True, upload_to='faq')),
            ],
        ),
    ]
