# Generated by Django 2.2.12 on 2020-04-20 05:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(default='user.png', upload_to='profile_pic/students')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, default='user.png', null=True, upload_to='profile_pic/instructors')),
                ('about_yourself', models.TextField(blank=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('bank_account_name', models.CharField(blank=True, max_length=300, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=300)),
                ('bank_account_number', models.CharField(blank=True, max_length=20, null=True)),
                ('IFSC_code', models.CharField(blank=True, max_length=15, null=True)),
                ('total_credits', models.PositiveIntegerField(default=0)),
                ('credits_15', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
