# Generated by Django 2.2.12 on 2020-05-06 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200430_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='bank_account_type',
            field=models.CharField(default='Saving', max_length=200),
        ),
    ]
