# Generated by Django 2.2.12 on 2020-05-06 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200506_1523'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moneytransfer',
            old_name='tranfered',
            new_name='transfered',
        ),
    ]
