# Generated by Django 2.2.12 on 2020-05-13 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20200508_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic/instructors'),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_pic',
            field=models.ImageField(upload_to='profile_pic/students'),
        ),
    ]
