# Generated by Django 2.2.12 on 2020-05-13 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20200513_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='profile_pic',
            field=models.ImageField(blank=True, default='https://musilearn-bucket.s3.amazonaws.com/static/img/user.png', null=True, upload_to='profile_pic/instructors'),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_pic',
            field=models.ImageField(default='https://musilearn-bucket.s3.amazonaws.com/static/img/user.png', upload_to='profile_pic/students'),
        ),
    ]
