# Generated by Django 2.2.12 on 2020-04-26 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_length_in_min',
            field=models.IntegerField(default=1),
        ),
    ]
