# Generated by Django 2.2.12 on 2020-04-28 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='token',
        ),
        migrations.AddField(
            model_name='order',
            name='txn_id',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
